### ISSUE TITLE
wait-for-expect dependency throws Cannot read property 'now' of undefined

### ISSUE THREAD

**Issue by freedomlang** [kentcdodds/dom-testing-library#194]
- `mocha` version: 5.2.0
- `chai` version: 4.2.0
- `jsdom` version: 13.1.0
- `jsdom-global` version: 3.0.2 
- `dom-testing-library` version: 3.16.4
- `react-testing-library` version: 5.4.4
- `react` version: 16.7.0
- `node` version: 9.11.1
- `npm` (or `yarn`) version: 6.5.0

### What you did:

I got the error below after running `npm test`.

### What happened:

```
> mocha --require jsdom-global/register --require @babel/register "./{packages,examples}/*/!(node_modules)/**/__test__/*.js"

node_modules/wait-for-expect/lib/index.js:16
    now = _ref.Date.now;
                    ^

TypeError: Cannot read property 'now' of undefined
    at Object.<anonymous> (node_modules/wait-for-expect/lib/index.js:16:21)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Module._compile (node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Object.newLoader [as .js] (node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (node_modules/dom-testing-library/dist/wait.js:10:45)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Module._compile (node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Object.newLoader [as .js] (node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (node_modules/dom-testing-library/dist/index.js:83:13)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Module._compile (node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Object.newLoader [as .js] (node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (node_modules/react-testing-library/dist/index.js:17:26)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Module._compile (node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Object.newLoader [as .js] (node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (examples/image-example/src/__test__/index.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Module._compile (node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Object.newLoader [as .js] (node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

### Reproduction:

It can reproduce in branch `test/image-example` of `draft-js-plugins/next`

**Comment by ryandrewjohnson** [comment]
I'm not sure if this will help you, but I was having the same issue. I'm not sure if it's specific to using [jsdom-global](https://github.com/rstacruz/jsdom-global), which I'm using in my project. But I had to manually initialize the Date object on window like so in my `jest.setup.js`, and then I was good. 

```javascript
require('jsdom-global')();
window.Date = Date;
```

**Comment by kentcdodds** [comment]
Hi friends 👋

I think it's odd to look for `Date` on `window`. This should be reported in `wait-for-expect` which is the module where this is happening (based on the stack trace).

**Comment by jdleesmiller** [comment]
I also hit this when loading `dom-testing-library` without `jest` but instead with `jsdom`.

Just setting `window.Date` as suggested above did not seem to work for me.

What did work was to set up JSDOM manually with the `runScripts: 'outside-only'` option mentioned in [the docs](https://github.com/jsdom/jsdom/tree/699ed6b7bea3354bf7cd7c8f174193238999cda8#executing-scripts):
```js
require('jsdom-global')('', {
  // Work around missing window.Date
  // https://github.com/testing-library/dom-testing-library/issues/194
  runScripts: 'outside-only'
})
```
I put this in a file `test/setup.js` and added `--require test/setup` to my mocha options instead of `--require jsdom-global/register`.

Related:
- Introduced in https://github.com/TheBrainFamily/wait-for-expect/pull/13, which is trying to work around other libraries (notably jest) mocking the global `Date.now` (https://github.com/TheBrainFamily/wait-for-expect/issues/12). The approach came from https://github.com/TheBrainFamily/wait-for-expect/issues/4 .
- https://github.com/TheBrainFamily/wait-for-expect/issues/17#issuecomment-493107110 (also found this solution)
- https://github.com/TheBrainFamily/wait-for-expect/issues/15

Idea: the library could avoid using `Date.now` at all --- the timeout doesn't need to be enforced very precisely, so it could just check number of elapsed intervals < timeout / interval; then it would only depend on having a working `setTimeout`, which would avoid the problem we have here with `window.Date` not existing by default with jsdom.

**Comment by kentcdodds** [comment]
Could you explain your idea a little further? I'm not sure I understand your suggestion.

**Comment by jdleesmiller** [comment]
It is probably easiest to explain in a PR: https://github.com/TheBrainFamily/wait-for-expect/pull/21 .
